class_path: lightning_diffusers.models.MnistDDPMModule
init_args:
  unet:
    class_path: diffusers.models.UNet2DModel
    init_args:
      sample_size: 32
      in_channels: 1
      out_channels: 1
      block_out_channels:
        - 64
        - 128
        - 256
        - 512
      layers_per_block: 3
      down_block_types:
        - DownBlock2D
        - DownBlock2D
        - DownBlock2D
        - DownBlock2D
      up_block_types:
        - UpBlock2D
        - UpBlock2D
        - UpBlock2D
        - UpBlock2D
  noise_scheduler:
    class_path: diffusers.schedulers.DDPMScheduler
    init_args:
      num_train_timesteps: 500
      beta_start: 1e-4
      beta_end: 0.02
